version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: .env
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - .:/app
    networks:
      - argocd-poc.network

networks:
  argocd-poc.network:
    driver: bridge